source 'https://github.com/CocoaPods/Specs.git'

target 'Weather' do

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  pod 'Firebase/Core'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'DevSupport', 'RCTNetwork', 'RCTImage']
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end